### ISSUE TITLE
How to get OfferingId and BusinessId

### ISSUE THREAD

**Issue by anizeani** [encointer/encointer-node#104]
How can I get the BusinessId and OfferingId (with the rust client and with polkadot-js, I don't see how to get it and I also don't get, why the rpc call requires the offering&businessId but when talking to the rust client in the cli it doesn't)?

**Comment by clangenb** [comment]
The `BusinessId` is derived by an `AccountId` and the community identifier if you look at the rust code:

https://github.com/encointer/pallets/blob/7e7a06cc21bb585d597f5d0f8cf5b1275003f3b4/primitives/src/bazaar.rs#L32-L38

Which is why the rust client does not need it explicitly because it generates it under the hood.

The `OfferingId` is not stored anywhere but in the key of double map of the offering registry. And you are right, I think this is a flaw in the implementation. I don't see a way to get the `OfferingId` without problems. I think we need an extra mapping here.

**Comment by clangenb** [comment]
See: https://github.com/encointer/pallets/issues/57
