### ISSUE TITLE
fee payment in community currency

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#147]
To be more inclusive, community members should be able to join without holding KSM/ERT. This will also allow that existing members can invite newbies by just sending them a fraction of their community income

With this, fees are automatically adjusted to purchasing-power

Statemine does that with this pallet
https://github.com/paritytech/substrate/tree/master/frame/transaction-payment/asset-tx-payment

We may have to implement additional traits such that our encointer-balances pallet qualifies as an asset to pay fees with

# requirements

* user can choose to pay fees in KSM or any community currency (CC) (possibly add an `Option<CommunityIdentifier>` argument to encointer pallet extrinsics???)
* a transaction in CC_A can also be paid in CC_B (think bootstrapping a neighboring community, where bootstrappers need to be able to register but don't necessarily own KSM and their CC is still at 0 money supply at that stage)

fee conversion:
```
CCfee = KSMfee * factor * reward(cid)
```
where 
* `factor` is a global storage variable with a CeremonyMaster-authorized setter fn. Initialize this factor at genesis to make a 5uKSM fee become a 0.01CC fee if the reward is set to 20.
* `reward(cid)` is the communit-issued income per ceremony. individual for each cid

**Comment by clangenb** [comment]
I see the current tasks to do this:

**Base Implementation**
* Implement all the [fungibles](https://github.com/paritytech/substrate/blob/master/frame/assets/src/impl_fungibles.rs) traits for `pallet-encointer-balances`. This will require to extend the encointer-balances pallet quite a bit.
* Implement [BalanceConversion](https://github.com/paritytech/substrate/blob/8e0dbe7a3ff961634df9db7d384012d5150423c1/frame/assets/src/types.rs#L242) to convert native tokens to the respective community currency.
* Implement [HandleCredit](https://github.com/paritytech/cumulus/blob/f6fa46091179098234b0a44d753b47fd3f82a263/polkadot-parachains/parachains-common/src/impls.rs#L75) to define what happens with the fees (treasury, burn, etc.)

**Runtime Integration**
The runtime integration should be fairly simple, we can use the already existing [asset-tx-payment](https://github.com/paritytech/substrate/tree/master/frame/transaction-payment/asset-tx-payment). We should only need to add the following sections to the runtime:

Example in statemine: https://github.com/paritytech/cumulus/blob/b468d0c33eac0adda27080b59ea9b5986ce6469b/polkadot-parachains/statemine/src/lib.rs#L494

```
impl pallet_asset_tx_payment::Config for Runtime {
	type Fungibles = EncointerBalances;
	type OnChargeAssetTransaction = pallet_asset_tx_payment::FungiblesAdapter<
		pallet_encointer_balances::BalanceToCommunityBalance<Balances, Runtime, ConvertInto>, // <---- from encointer-balances
		CustomHandleCredit<Runtime>,   // <---- from encointer-balances, or defined per runtime
	>;
}

/// The SignedExtension to the basic transaction logic.
pub type SignedExtra = (
        .... default stuff
        // the following wraps the normal `pallet_transaction_payment` and uses
        // the community currency, with the CID given in the tx, which is resolved
        // with `pallet_encointer_balances::BalanceToCommunityBalance`
	pallet_asset_tx_payment::ChargeAssetTxPayment<Runtime>, 
);
```

**Other Tasks**
* substrate-api-client: allow generic signed extra; otherwise we will not be able to send extrinsics at all, probably.
* encointer-wallet: also implement handling of custom signed extra

**Comment by pifragile** [comment]
@clangenb i have a general question. how will we be able to determine an exchange rate between the native currency and the community currency?
does `ConvertInto` in `pallet_encointer_balances::BalanceToCommunityBalance<Balances, Runtime, ConvertInto>`  mean that we just take the same number? i.e if the fee was 0.0001 KSM, it will be converted to 0.0001 LEU?

this would somehow match the logic of `With this, fees are automatically adjusted to purchasing-power`

but still unsure, please explain.

**Comment by clangenb** [comment]
Not quite:

> i.e if the fee was 0.0001 KSM, it will be converted to 0.0001 LEU?

I think this is not adjusted to purchasing power because it doesn't incorporate any fundamental metric of the local currency, e.g. total supply, nominal income, demurrage. How exactly we want to tune the fees might need some more thinking. As a first step, I would just take a fraction of the nominal income.

For now, I would suppose the current model:

Nominal Income = 22 LEU.
We recommend 1 LEU = 1 CHF.
Transaction fees are  around 5microKSM (=0.00073 CHF) for a simple transfer tx.

So let's say we want users to have Zurich purchasing power in terms of transaction fees:

22 / (0.00073/5) ~ 150'000 NominalIncome/microKSM

Hence, we could apply a formula like: `ConversionFactor_community = Nominal Income/150'000.`

This approach has downfalls because demurrage and total supply are neglected, but it might make sense as a first approach.

**Comment by brenzi** [comment]
Please define fees to be a fixed ratio of a community's ceremony reward. KSM fees should stay how they are. No need to relate KSM to CC exchange rate.
I'd suggest a simple xfer to cost 0.01 LEU assuming an initial ceremony reward of 20LEU per ceremony. Less makes no sense to me as its barely noticeable already

The ratio needs to be adjustable by council origin

**Comment by clangenb** [comment]
I have doubts using such a simple approach, but I could not find hard reasons against it so far.

**Comment by brenzi** [comment]
let's start simple and extend as needed

I see game-theoretical upsides of the simple approach because it makes local currencies in low wage countries attractive to users in high-wage countries which could lead to the first world backing community currencies in the global south
