### ISSUE TITLE
subsidiary democracy

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#193]
Implenent One-person-one-vote democracy based on ceremony attendance

A reputation of at least X% of the last N ceremonie is necessary to be allowed to vote.

N is reputation lifetime
X is a newly defined parameter, defaulting to 50%

Anyone with enough reputation may  submit a proposal to be voted on

Proposals need a supermajority (similar to polkadot referendums). The fewer people vote, the higher the support has to be.

# subsidiarity

Every decision is taken at the lowest level possible.

Community parametere changes are voted on by the community

New communities need to be approved by a majority of existing communities (or reputables?)

Changes in ceremony schedule or treasury spends also need global approval

**Comment by brenzi** [comment]
And consider "conviction voting" as a concept to protect the interests of minorities

**Comment by pifragile** [comment]
The plan so far (this is subject to change).

- There will be 3 different types of votes:
  1. Community Level
  2. Global Level (Majority of total votes)
  3.  Global Level (Majority of communities, which hold internal votes)
  (Design details involving Quorum biases etc. TBD)
This list is not exhaustive and our system should be extensible to capture different types of vote logic(eg. More or less reputation needed to vote, different quorum biases)

- Proposals consist of a Dispatchable and a desired Origin from which the Dispatchable should be called
- We use Substrate's `Referenda` pallet for referenda
- We use Substrates's `Scheduler` pallet for proposal enactment
- The core piece of our democracy system will be a pallet that gathers votes for referenda.
  - For every Origin decide who is allowed to vote (eg. only community members can vote for proposals regarding their community)
  - Implement logic for Community Majority (type 3) votes
  - Use custom `Tally` implementation to capture vote logic

Next Steps:
- Reevaluate this plan in terms of feasibility and compare with other possible options (eg. building everything from scratch)
- Define "MVP"
- Define tasks for MVP implementation
- Define timeline and MVP testing strategy (eg. with EDI in SCS)

Vision:
Build and roll out a simple version(MVP) of the democracy system in a test environment(eg. EDI). Evaluate the system  and make design tweaks as needed. After another implementation phase, roll out again to EDI and hopefully we will be happy with the result (otherwise make another iteration). Based on the experience in EDI, fine-tune the parameters (eg. reputation threshold, quorum biases) and deploy to LEU. Building more features on top of the MVP can happen after deployment to LEU or can even start between EDI test runs.

**Comment by pifragile** [comment]
I just noticed that the `Referenda` Pallet does not support Adaptive Quorum Biasing. This will have to be the first thing to do when working again on this issue. Do we need it? Why did Substarte not implement it in the `Referenda` Pallet? If we want it, can we implement it as custom logic in our voting pallet?

**Comment by pifragile** [comment]
In the meantime I changed my mind about using the  `Referenda` pallet and I think it makes more sense to build the entire thing from scratch. `Referenda`  has too many things we don't (necessarily) need, like decision deposit, preparation period,  the notion of different tracks, or descending approval/turnout thresholds over time. Even if we might need them later we can implement it ourselves. Also `Referenda` does not support Adaptive Quorum Biasing. I think we will be more flexible if we do it ourselves. 

The architecture is see as follows:

- Proposal Submission
  - Register Preimage of Dispatchable
  - Submit Proposal (Hash + Desired origin) (*)
  - Pay fee
  - Schedule alarm for end of vote
- Voting
  - Check if voter is allowed to for for this proposal (eg. Are they community members) (*)
  - Different Vote types (local majority, global majority, community majority)
  - Voting Period
    - Fixed (*)
    - Custom Logic
- Proposal Enactment
  - Check if the proposal is passing
    - Simple majority (*)
    - Supermajority
    - Mix? (For community majority)
  - Actual dispatch
    - Scheduled
    - Dispatch right away (*)
  - Extrinsic to trigger enactment process (*)

The parts marked with a (*) I would consider MVP features. The other features will be added later on after a first testing stage.

**Comment by pifragile** [comment]
Closed in favor of https://github.com/encointer/pallets/issues/258
