### ISSUE TITLE
Cannot register new currency

### ISSUE THREAD

**Issue by clangenb** [encointer/encointer-node#32]
I tried to register a new currency at Gesell but the `EcointerCurrencies::new_currency` extrinsic hangs. A subsequent try results in an extrinsic error: `extrinsic error code 1014: Priority is too low: (30299 vs 30299)`

Procedure that results in this:
* Create three accounts in encointer-app. Use the app's faucet to give them some funds.
* Create another account with the `encointer-client`. use cli to give some funds.
* Try to register the new currency with the following json file:

```
{
  "type": "FeatureCollection",
    "currency_meta": {
    "name": "Meilen",
    "bootstrappers": [
      "5DSGzGh1A9AE5M8Jvb2bnc4Q92LGfoJ9SfLAuUkXGp2YxqCp",
      "5Hb5XaSntMNTRrnZLXDz4GGF6JzwwAw2fssmVPfYwWXQ7VCY",
      "5ER6Z9sEFKR4kZj8PN8LvWykLaxvMEzkSC8rPzz6dXuAyG68",
      "5FTm8eYw3hidS1V6jRDxUvoMz7ENkmrcqHiCCh9XM47ppXnL"
    ]
  },
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          8.640167713165283,
          47.270552054744066
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          8.64399790763855,
          47.26961293731949
        ]
      }
    }
  ]
}
```

**Comment by clangenb** [comment]
Could reproduce it locally.

panics at `pallet_encointer_currencies::Module<T>::haversine_distance`

starting to investigate

**Comment by clangenb** [comment]
Interesting. from above panic I thought it was due to the location. But a unit test with these two locations successfully registers a new currency.

**Comment by clangenb** [comment]
Nevermind. I put in the wrong numbers, the unit test now fails. Investigating in https://github.com/encointer/pallets/tree/bugfix/new_currency_fails_at_harvesine_distance

**Comment by brenzi** [comment]
have you tried to register locations that are further apart from actually registered ones?

**Comment by clangenb** [comment]
The error comes from the two locations being to close together, which leads to an error in the substrate-fixed library: https://github.com/encointer/substrate-fixed/issues/6

**Comment by clangenb** [comment]
The error comes from an overflow while inverting the operand, see https://github.com/encointer/substrate-fixed/issues/6.

So we have two options:
* either change the type of `Degree` from `I32F32` to `I64F64`
* increase the minimum allowed distance for two locations up to ~1000m

**Comment by brenzi** [comment]
We should be careful with bloating type sizes because we aim at millions of locations registered. But we must also be careful to enable plausible population sizes.

For plausibility, The city of Zurich has an area of 87.88km2 and a popluation density of 4700/km2, so we'd need 4700/12 = 392 meetups/km2, so roughly 2550m2 per meetup. Dividing Zurich into equilateral triangles, the distance between two meetups would be

2*ri = 2*sqrt(4A/sqrt(3))/(2*sqrt(3)) = 44.3m

For 100% participation of course. Also: equidistant scattering of meetup places renders inacessible locations....

By reverse logic, 1000m minimum distance would imply an area of 1.3m2 and allow for a population of 87.88km2/1.3km2/meetup*12participants/meetup = 803 participants. Clearly not satisfying!

Conclusion:
I suggest we go for `I64F64`.

@clangenb please review my math

**Comment by clangenb** [comment]
I agree with your numbers; hence I also suggest that we go for `I64F64`.

**Comment by brenzi** [comment]
resolved in pallets commit: https://github.com/encointer/pallets/commit/9ca66f96484a1a3c08aaa896be0d8ded99c6eef7
